const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const caseSchema = new Schema({
  name: { type: String,  },
  dateOfBirth: { type: Date, },
  sex: { type: String , },
  height: { type: Number,  },
  drivingLicenseNo: { type: String , },
  pvcNo: { type: String , },
  ninNo: { type: String , },
  nationalIdNo: { type: String , },
  passportNo: { type: String , },
  issuingAuthority: { type: String , },
  nationality: { type: String , },
  address: { type: String , },
  city: { type: String , },
  state: { type: String , },
  telephoneNo: [{ type: String }],
  injuryOrDisability: { type: String },
  dateOfOffence: { type: Date },
  timeOfOffence: { type: String },
  locationOfOffence: { type: String },
  offenceType: { type: String },
  penaltiesOrFine: { type: String },
  typeOfCar: { type: String },
  carRegistration: { type: String },
  carColour: { type: String },
  nameOfInsurance: { type: String },
  insNo: { type: String },
  expiryDate: { type: Date },
  vehicleRoadWorthinessNo: { type: String },
  vehicleRoadWorthinessExpiryDate: { type: Date },
  chassisNo: { type: String },
  arrestingOfficerBadgeNo: { type: String },
  arrestingOfficersName: { type: String },
  arrestingAgency: { type: String },
  policeStationAddress: { type: String },
  offenderStatement: { type: String },
  officersStation: { type: String },
  propertiesInPoliceSafe: { type: String },
  policeSafeNo: { type: String },
  policeReleaseDate: { type: Date },
  bailDate: { type: Date },
  guarantorName: { type: String },
  dpoName: { type: String },
  cidName: { type: String },
  cidStatement: { type: String },
  solicitorOrLawyerName: { type: String },
  solicitorOrLawyerAddress: { type: String },
  solicitorOrLawyerContactDetails: { type: String },
  courtDate: { type: Date },
  courtAddress: { type: String },
  judgmentOrSentencingOrFine: { type: String },
  judgeName: { type: String },
  propertiesInPrisonSafe: { type: String },
  prisonSafeNo: { type: String },
  jailDate: { type: Date },
  prisonAddress: { type: String },
  prisonerNo: { type: String },
  prisonReleaseDate: { type: Date },
  prisonState: {type: String}
});

const Case = mongoose.model('cases', caseSchema);
module.exports = Case;